name: paraeta-la-medrana
services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRESDB_USER}
      - POSTGRES_PASSWORD=${POSTGRESDB_PASSWORD}
      - POSTGRES_DB=${POSTGRESDB_DATABASE}
    volumes:
      - starter-postgresdb:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - back-starter-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRESDB_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
  back:
    depends_on:
      - postgresdb
    build:
      context: .
      dockerfile: apps/back/Dockerfile
    container_name: back
    restart: unless-stopped
    environment:
      - NODE_PORT=${NODE_PORT:-3200}
      - POSTGRESDB_USER=${POSTGRESDB_USER}
      - POSTGRESDB_PASSWORD=${POSTGRESDB_PASSWORD}
      - POSTGRESDB_DATABASE=${POSTGRESDB_DATABASE}
      - POSTGRESDB_PORT=${POSTGRESDB_PORT:-5432}
      - POSTGRESDB_HOST=postgresdb
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-1h}
      - JWT_REFRESH_EXPIRES_IN=${JWT_REFRESH_EXPIRES_IN:-7d}
      - HASH_SALT_ROUNDS=${HASH_SALT_ROUNDS:-10}
      - NODE_PRODUCTION=${NODE_PRODUCTION:-true}
      - NODE_UPLOAD_FILES=${NODE_UPLOAD_FILES:-uploads}
    networks:
      - back-starter-network
    volumes:
      - upload_files:/home/back/${NODE_UPLOAD_FILES:-uploads}
      - tmp:/tmp
  front:
    build:
      context: .
      dockerfile: apps/front/Dockerfile
    container_name: front
    depends_on:
      - back
    restart: unless-stopped
    environment:
      - SERVICE_FQDN_FRONT=https://paraetamedrana.dani-herrero.es
    networks:
      - back-starter-network

volumes:
  starter-postgresdb:
  upload_files:
  tmp:

networks:
  back-starter-network:
